from __future__ import annotations

from typing import Any, Optional, Union, Sequence

import numpy as np

from .colorbar import Colorbar

ArrayLike = np.ndarray | list[float] | tuple[float, ...]
ColorLike = Union[str, Sequence[float], Sequence[Sequence[float] | ArrayLike], np.ndarray, None]
LineStyle = str
MarkerStyle = str


class Axes3:
    def __init__(self, nrows: int, ncols: int, index: int, fig: Any) -> None: ...
    def plot(self, xs: Union[ArrayLike, float, int], ys: Union[ArrayLike, float, int], zs: Union[ArrayLike, float, int], zdir: str = ..., **kwargs: Any) -> Any: ...
    def scatter(self, xs: Union[ArrayLike, float, int], ys: Union[ArrayLike, float, int], zs: Union[ArrayLike, float, int] = ..., zdir: str = ..., *args: Any, **kwargs: Any) -> Any: ...
    def plot_surface(self, X: np.ndarray, Y: np.ndarray, Z: np.ndarray, **kwargs: Any) -> Any: ...
    def plot_wireframe(self, X: np.ndarray, Y: np.ndarray, Z: np.ndarray, **kwargs: Any) -> Any: ...
    def errorbar(self, x: Union[ArrayLike, float, int], y: Union[ArrayLike, float, int], z: Union[ArrayLike, float, int], zerr: Optional[Union[ArrayLike, float, int] | float] = ..., yerr: Optional[Union[ArrayLike, float, int] | float] = ..., xerr: Optional[Union[ArrayLike, float, int] | float] = ..., **kwargs: Any) -> Any: ...
    def fill_between(self, x1: Union[ArrayLike, float, int], y1: Union[ArrayLike, float, int], z1: Union[ArrayLike, float, int], x2: Union[ArrayLike, float, int], y2: Union[ArrayLike, float, int], z2: Union[ArrayLike, float, int], *, alpha: Optional[float] = ..., color: Optional[ColorLike] = ..., c: Optional[ColorLike] = ..., label: Optional[str] = ...) -> Any: ...
    def text(self, x: float, y: float, z: float, s: str, **kwargs: Any) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_xlabel(self, label: str) -> None: ...
    def set_ylabel(self, label: str) -> None: ...
    def set_zlabel(self, label: str) -> None: ...
    def set_xlim(self, *args: Any, **kwargs: Any) -> None: ...
    def set_ylim(self, *args: Any, **kwargs: Any) -> None: ...
    def set_zlim(self, *args: Any, **kwargs: Any) -> None: ...
    def set_xscale(self, *args: Any, **kwargs: Any) -> None: ...
    def set_yscale(self, *args: Any, **kwargs: Any) -> None: ...
    def set_zscale(self, *args: Any, **kwargs: Any) -> None: ...
    def set_xticks(self, ticks: Any, labels: Any = ...) -> None: ...
    def set_yticks(self, ticks: Any, labels: Any = ...) -> None: ...
    def set_zticks(self, ticks: Any, labels: Any = ...) -> None: ...
    def set_xticklabels(self, labels: Any) -> None: ...
    def set_yticklabels(self, labels: Any) -> None: ...
    def set_zticklabels(self, labels: Any) -> None: ...
    def legend(self, *args: Any, **kwargs: Any) -> None: ...
    def view_init(self, elev: Optional[float] = ..., azim: Optional[float] = ..., roll: Optional[float] = ...) -> None: ...
    def grid(self, visible: bool = ..., which: str = ...) -> None: ...
    def set(self, **kwargs: Any) -> None: ...