from .config import TikzConfig as TikzConfig
from .state import main_name as main_name, next_export_num as next_export_num

class Graph:
    pass
    """    def __init__(self, axes, coordinates, settings=None, xerr=None, yerr=None, path_name=None, **style) -> None: ...
    def save_data(self, points, filename): ...
    def to_tex(self, filename): ...
    def data_range(self, which): ...
    def get_erange(self, which): ...
    def filter(self, which, value) -> None: ..."""
