from typing import Literal

StyleName = Literal["empty", "default", "classic", "tableau", "colorblind10", "ggplot", "538", "seaborn", "bmh", "dark_background"]

class Styles:
    def __init__(self) -> None: ...
    def use(self, style: StyleName) -> None: "Style setting"
    def _get_style(self) -> str: ...
    def _get_color_cycle(self) -> list[str]: ...
    def _get_grid_cycle(self) -> dict[str, str] | None: ...
    def _get_background_cycle(self) -> str | None: ...
